import { StyleSheet } from "react-native";
import { colors } from "../../utils/helpers";

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },

  hero: { backgroundColor: colors.primary, margin: 16, borderRadius: 16, padding: 20 },
  heroLabel: { color: "rgba(255,255,255,0.7)", fontSize: 13, marginBottom: 12 },
  heroRow: { flexDirection: "row" },
  heroItem: { flex: 1 },
  heroDivider: { width: 1, backgroundColor: "rgba(255,255,255,0.2)", marginHorizontal: 16 },
  heroItemLabel: { color: "rgba(255,255,255,0.6)", fontSize: 11 },
  heroItemValue: { color: "#fff", fontSize: 20, fontWeight: "700", marginTop: 4 },

  card: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 16,
    marginBottom: 10,
  },
  catDot: { width: 4, borderRadius: 2, marginRight: 12 },
  cardContent: { flex: 1 },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  cardTitle: { fontSize: 15, fontWeight: "700", color: colors.text },
  cardActions: { flexDirection: "row", gap: 4 },
  actionBtn: { padding: 4 },
  amountRow: { flexDirection: "row", alignItems: "baseline", marginBottom: 8, gap: 4 },
  spent: { fontSize: 16, fontWeight: "700", color: colors.text },
  limit: { fontSize: 13, color: colors.textMuted },
  pct: { fontSize: 12, fontWeight: "700", marginLeft: "auto" },
  progressBg: {
    height: 8,
    backgroundColor: colors.surfaceSecondary,
    borderRadius: 4,
    overflow: "hidden",
    marginBottom: 6,
  },
  progressFill: { height: "100%", borderRadius: 4 },
  remaining: { fontSize: 11, color: colors.textMuted },

  empty: { alignItems: "center", paddingTop: 60, gap: 8 },
  emptyText: { fontSize: 16, color: colors.textSecondary, fontWeight: "600" },
  emptySubText: { fontSize: 13, color: colors.textMuted },

  fab: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
});

export const fm = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  headerTitle: { fontSize: 17, fontWeight: "700", color: colors.text },
  cancel: { fontSize: 16, color: colors.textSecondary },
  save: { fontSize: 16, color: colors.primary, fontWeight: "700" },
  body: { flex: 1, backgroundColor: colors.background, padding: 16 },
  label: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textMuted,
    marginBottom: 6,
    marginTop: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    color: colors.text,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoBox: { backgroundColor: colors.surfaceSecondary, borderRadius: 10, padding: 12, marginBottom: 4 },
  infoText: { fontSize: 15, color: colors.text, fontWeight: "600" },
  row: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  catChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipText: { fontSize: 13, color: colors.textSecondary, fontWeight: "600" },
  chipTextSelected: { color: "#fff" },
  scrollSpacer: { marginBottom: 16 },
  flex1: { flex: 1 },
  savingOpacity: { opacity: 0.5 },
});
