import { StyleSheet } from "react-native";
import { colors } from "../../utils/helpers";

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  hero: { backgroundColor: colors.warning, margin: 16, borderRadius: 16, padding: 20 },
  heroLabel: { color: "rgba(0,0,0,0.5)", fontSize: 13 },
  heroAmount: { color: "#fff", fontSize: 32, fontWeight: "800", marginTop: 4 },
  heroSub: { color: "rgba(255,255,255,0.7)", fontSize: 13, marginTop: 4 },
  card: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  cardInactive: { opacity: 0.55 },
  iconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  cardContent: { flex: 1 },
  cardRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 6,
  },
  cardTitle: { fontSize: 15, fontWeight: "700", color: colors.text },
  provider: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
  cardActions: { flexDirection: "row", gap: 4 },
  actionBtn: { padding: 4 },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  badge: { flexDirection: "row", alignItems: "center", gap: 4 },
  badgeText: { fontSize: 12, color: colors.textMuted },
  amount: { fontSize: 16, fontWeight: "700", color: colors.text },
  category: { fontSize: 12, color: colors.textMuted },
  inactive: { fontSize: 11, color: colors.danger, marginTop: 2, fontWeight: "600" },
  empty: { alignItems: "center", paddingTop: 60, gap: 8 },
  emptyText: { fontSize: 16, color: colors.textSecondary, fontWeight: "600" },
  emptySubText: { fontSize: 13, color: colors.textMuted },
  fab: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.warning,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
});

export const fm = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  headerTitle: { fontSize: 17, fontWeight: "700", color: colors.text },
  cancel: { fontSize: 16, color: colors.textSecondary },
  save: { fontSize: 16, color: colors.primary, fontWeight: "700" },
  body: { flex: 1, backgroundColor: colors.background, padding: 16 },
  label: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textMuted,
    marginBottom: 6,
    marginTop: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    color: colors.text,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  colorRow: { flexDirection: "row", gap: 10, flexWrap: "wrap", marginBottom: 4 },
  colorDot: { width: 32, height: 32, borderRadius: 16 },
  colorDotActive: { borderWidth: 3, borderColor: colors.text },
  row: { flexDirection: "row", gap: 8 },
  catChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipText: { fontSize: 13, color: colors.textSecondary, fontWeight: "600" },
  iconChip: {
    width: 48,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    justifyContent: "center",
    alignItems: "center",
  },
  toggleBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  toggleBtnActive: { backgroundColor: colors.success, borderColor: colors.success },
  toggleText: { fontSize: 15, color: colors.textSecondary, fontWeight: "600" },
  scrollSpacer: { marginBottom: 16 },
});
