import { StyleSheet } from "react-native";
import { colors } from "../../utils/helpers";

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  emptyText: { textAlign: "center", color: colors.textMuted, marginTop: 40, fontSize: 16 },

  summary: { flexDirection: "row", paddingHorizontal: 16, paddingTop: 16, gap: 10 },
  summaryCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 12, padding: 14 },
  summaryLabel: { fontSize: 12, color: colors.textMuted },
  summaryValue: { fontSize: 18, fontWeight: "700", marginTop: 4 },

  filterRow: { flexDirection: "row", padding: 16, gap: 8 },
  filterBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterBtnActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  filterText: { fontSize: 13, color: colors.textSecondary, fontWeight: "600" },
  filterTextActive: { color: "#fff" },

  card: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  iconBox: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  cardInfo: { flex: 1 },
  cardTitle: { color: colors.text, fontWeight: "600", fontSize: 14 },
  cardMeta: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  cardSubMeta: { color: colors.textMuted, fontSize: 10, marginTop: 1 },
  cardRight: { alignItems: "flex-end", justifyContent: "space-between" },
  amount: { fontWeight: "700", fontSize: 15 },
  categoryIconText: { fontWeight: "700" },
  actions: { flexDirection: "row", gap: 4, marginTop: 4 },
  actionBtn: { padding: 4 },
  listContent: { padding: 16, paddingBottom: 100 },

  fab: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
});

export const fm = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.surface,
  },
  headerTitle: { fontSize: 17, fontWeight: "700", color: colors.text },
  cancel: { fontSize: 16, color: colors.textSecondary },
  save: { fontSize: 16, color: colors.primary, fontWeight: "700" },
  body: { flex: 1, backgroundColor: colors.background, padding: 16 },
  label: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textMuted,
    marginBottom: 6,
    marginTop: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    padding: 12,
    fontSize: 15,
    color: colors.text,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: colors.border,
  },
  row: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipActive: { backgroundColor: colors.primary, borderColor: colors.primary },
  chipText: { fontSize: 13, color: colors.textSecondary, fontWeight: "600" },
  chipTextActive: { color: "#fff" },
  catChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  chipTextSelected: { color: "#fff" },
  inputMultiline: { height: 80, textAlignVertical: "top" as const },
  flex1: { flex: 1 },
  savingOpacity: { opacity: 0.5 },
  scrollSpacer: { marginBottom: 16 },
});
